async function webQuestion(title,initial,options){return new Promise(resolve=>{const dialog=document.createElement('dialog');const form=document.createElement('form');const heading=document.createElement('h2');heading.textContent=title;form.append(heading);const input=document.createElement(options?'select':'input');input.setAttribute('aria-label',title);if(options)for(const value of options){const item=document.createElement('option');item.value=value;item.textContent=({Local:'Solo esta empresa',Global:'Catálogo global',backup:'Descargar respaldo de esta empresa',import:'Importar empresa del escritorio', 'global-backup':'Descargar catálogo global','global-import':'Importar catálogo global (espacio nuevo)'})[value]||value;input.append(item);}input.value=initial;input.required=true;form.append(input);const ok=document.createElement('button');ok.textContent='Continuar';const cancel=document.createElement('button');cancel.type='button';cancel.textContent='Cancelar';form.append(ok,cancel);dialog.append(form);document.body.append(dialog);const finish=v=>{dialog.close();dialog.remove();resolve(v);};form.onsubmit=e=>{e.preventDefault();finish(input.value);};cancel.onclick=()=>finish(null);dialog.oncancel=e=>{e.preventDefault();finish(null);};dialog.showModal();input.focus();});}
let unlock;window.ansoritoReady=new Promise(r=>unlock=r);
const activeKey='ansorito-web-company';const voucherVersions=new Map();
async function chooseUpload(){return new Promise(resolve=>{const input=document.createElement('input');input.type='file';input.accept='.xls,.xlsx,.csv';input.oncancel=()=>resolve(null);input.onchange=async()=>{const file=input.files[0];if(!file)return resolve(null);if(file.size>20*1024*1024){alert('El archivo excede 20 MB');return resolve(null);}const reader=new FileReader();reader.onload=()=>resolve({name:file.name,base64:reader.result.split(',')[1]});reader.readAsDataURL(file);};input.click();});}
async function download(token){const company=sessionStorage.getItem(activeKey)||'';const r=await fetch('/download/'+encodeURIComponent(token)+'?company='+encodeURIComponent(company));if(!r.ok)throw Error('No se pudo descargar el archivo');const blob=await r.blob();const link=document.createElement('a');link.href=URL.createObjectURL(blob);const name=/filename\*=UTF-8''(.+)/.exec(r.headers.get('content-disposition')||'')?.[1];link.download=name?decodeURIComponent(name):'exportacion';link.click();setTimeout(()=>URL.revokeObjectURL(link.href),60000);}
async function invokeWeb(channel,...args){const payload={channel,args,companyId:sessionStorage.getItem(activeKey),requestId:crypto.randomUUID()};
 if(channel==='voucher:update-completo'){const value=args[0];value.webVersion=voucherVersions.get(String(value.voucher_id??value.id));}
 if(channel==='empresa:seleccionar'){payload.companyName=await webQuestion('Nombre de la empresa','');if(!payload.companyName)return {success:false,canceled:true};}
 if(channel.endsWith(':import-excel')){payload.upload=await chooseUpload();if(!payload.upload)return {success:false,canceled:true};const scope=await webQuestion('Destino de importación','Local',['Local','Global']);if(scope===null)return {success:false,canceled:true};if(!['Local','Global'].includes(scope))throw Error('Escribe Local o Global');payload.scope=scope;}
 const request=()=>fetch('/rpc',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});let response;try{response=await request();}catch(e){if(channel!=='voucher:add')throw e;response=await request();}const result=await response.json();if(!response.ok)throw Error(result.error||'Error del servidor');
 if((channel.startsWith('empresa:')||channel==='web:import-database')&&result.companyId)sessionStorage.setItem(activeKey,result.companyId);
 const value=result.value;if(value?.webVersion&&value?.cabecera?.id)voucherVersions.set(String(value.cabecera.id),value.webVersion);if(value?.download&&(channel.includes(':guardar-')||channel.endsWith(':export-excel')||channel==='sire-sunat:descargar-archivo'))await download(value.download);
 return value;
}
document.addEventListener('DOMContentLoaded',async()=>{try{const config=await(await fetch('/config')).json();if(config.authenticated){unlock();addSessionTools(config);return;}
 sessionStorage.removeItem(activeKey);const panel=document.createElement('dialog');panel.innerHTML='<form><h2>Ingresar a Ansorito</h2><p>Usa tu cuenta de Supabase.</p><label>Correo <input name="email" type="email" required autocomplete="username"></label><p><label>Contraseña <input name="password" type="password" required autocomplete="current-password"></label></p><button>Ingresar</button><p role="status"></p></form>';document.body.append(panel);panel.addEventListener('cancel',e=>e.preventDefault());panel.showModal();panel.querySelector('form').onsubmit=async e=>{e.preventDefault();const form=new FormData(e.target);const r=await fetch('/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(form))});if(!r.ok){panel.querySelector('[role=status]').textContent='Revisa tu correo y contraseña.';return;}panel.close();panel.remove();unlock();addSessionTools(config);};}catch(e){alert('No se pudo iniciar Ansorito: '+e.message);}});
function addSessionTools(config){const bar=document.createElement('div');bar.style.cssText='position:fixed;bottom:8px;right:8px;z-index:5000;padding:6px 10px;background:#fff;color:#333;border:1px solid #ddd;border-radius:6px;font:12px sans-serif';bar.textContent=config.mode==='local'?'Revisión web local · datos de prueba':'Sesión Supabase';if(config.mode!=='local'){const button=document.createElement('button');button.textContent='Cerrar sesión';button.onclick=async()=>{await fetch('/logout',{method:'POST'});sessionStorage.clear();location.reload();};bar.append(' ',button);}const backups=document.createElement('button');backups.textContent='Respaldos';backups.onclick=()=>databaseTools().catch(e=>alert(e.message));bar.append(' ',backups);document.body.append(bar);}
async function databaseTools(){const choice=await webQuestion('Bases de datos y respaldos','backup',['backup','import','global-backup','global-import']);if(!choice)return;if(choice.includes('backup')){const r=await invokeWeb('web:backup-database',choice==='global-backup'?'global':'company');if(r.success)await download(r.download);return;}
 const name=choice==='global-import'?'Catálogo global':await webQuestion('Nombre de la empresa importada','');if(!name)return;const upload=await new Promise(resolve=>{const input=document.createElement('input');input.type='file';input.accept='.db,.sqlite,.sqlite3';input.oncancel=()=>resolve(null);input.onchange=()=>{const file=input.files[0];if(!file||file.size>20*1024*1024)return resolve(null);const reader=new FileReader();reader.onload=()=>resolve(reader.result.split(',')[1]);reader.readAsDataURL(file);};input.click();});if(!upload)return;const result=await invokeWeb('web:import-database',{name,kind:choice==='global-import'?'global':'company',base64:upload});if(result.success)location.reload();}
