const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');const Database=require('./sqlite.cjs');const {current}=require('./context.cjs');const db=require('../src/main/database/db');const {runMigrations}=require('../src/main/database/migrationRunner');const {EMPRESA_MIGRATIONS}=require('../src/main/database/migrations/empresa');const {GLOBAL_MIGRATIONS}=require('../src/main/database/migrations/global');
function importDatabase(input){const c=current(),global=input.kind==='global';const buffer=Buffer.from(String(input.base64||''),'base64');if(buffer.length>20*1024*1024||buffer.subarray(0,16).toString()!=='SQLite format 3\0')throw Error('Selecciona una copia SQLite válida (hasta 20 MB).');
 const name=String(input.name||'Empresa importada').trim();if(!name||name.length>100||/[\/\\\x00-\x1f]/.test(name))throw Error('Nombre de empresa inválido');
 if(global&&(db.companies().length||fs.existsSync(path.join(c.workspace,'global_contable.db'))))throw Error('Importa el catálogo global antes de crear empresas o cargar catálogos en este espacio.');
 const candidate=path.join(c.tempDir,'candidate.db');fs.writeFileSync(candidate,buffer);const conn=new Database(candidate);let summary;
 try{if(conn.pragma('integrity_check',{simple:true})!=='ok')throw Error('La base de datos está dañada');if(conn.prepare("SELECT name FROM sqlite_master WHERE type IN ('trigger','view')").all().length)throw Error('La copia contiene objetos no esperados');const tables=new Set(conn.prepare("SELECT name FROM sqlite_master WHERE type='table'").all().map(x=>x.name));for(const name of (global?['plan_cuentas','tipos_documentos','entidades']:['vouchers','voucher_detalles','config_empresa']))if(!tables.has(name))throw Error('La base no corresponde al formato de Ansorito');runMigrations(conn,global?GLOBAL_MIGRATIONS:EMPRESA_MIGRATIONS,{logger:{log(){},warn(){},error(){}}});summary=global?{}:{vouchers:conn.prepare('SELECT COUNT(*) AS n FROM vouchers').get().n,detalles:conn.prepare('SELECT COUNT(*) AS n FROM voucher_detalles').get().n};}finally{conn.close();}
 if(global){fs.renameSync(candidate,path.join(c.workspace,'global_contable.db'));return {success:true,kind:'global'};}
 const item={id:crypto.randomUUID(),name,publicPath:'/empresas/'+crypto.randomUUID()+'/'+name};const dir=path.join(c.workspace,'companies',item.id);fs.mkdirSync(dir,{recursive:true});fs.renameSync(candidate,path.join(dir,'contable.db'));const list=db.companies();list.push(item);fs.writeFileSync(path.join(c.workspace,'companies.json'),JSON.stringify(list));c.companyId=item.id;return {success:true,...db.getEstadoEmpresa(),...summary};
}
function backupDatabase(kind){const c=current();const conn=kind==='global'?db.getGlobalDB():db.getDB();const filename=kind==='global'?'global_contable.db':'empresa_contable.db';const target=path.join(c.tempDir,filename);conn.prepare('VACUUM INTO ?').run(target);return {success:true,filePath:target,fileName:filename};}
module.exports={importDatabase,backupDatabase};
