const {test,before,after}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs'),os=require('node:os'),path=require('node:path');
process.env.AUTO_EXCHANGE_RATE='0';
process.env.ANSORITO_DATA_DIR=fs.mkdtempSync(path.join(os.tmpdir(),'ansorito-web-test-'));
const {makeServer,handlers,storage}=require('./index.cjs');const db=require('../src/main/database/db');let server,base,cookie,company,second;
async function rpc(channel,args=[],extra={}){const r=await fetch(base+'/rpc',{method:'POST',headers:{Cookie:cookie,'Content-Type':'application/json'},body:JSON.stringify({channel,args,companyId:company,...extra})});const b=await r.json();assert.equal(r.status,200,JSON.stringify(b));return b;}
before(async()=>{server=makeServer();await new Promise(r=>server.listen(0,'127.0.0.1',r));base='http://127.0.0.1:'+server.address().port;const r=await fetch(base);cookie=r.headers.get('set-cookie').split(';')[0];});after(()=>new Promise(r=>server.close(r)));
test('Los 73 canales originales y los 2 canales de período están registrados',()=>{const preload=fs.readFileSync(path.join(__dirname,'../src/preload.js'),'utf8');const channels=[...preload.matchAll(/invoke\('([^']+)'/g)].map(x=>x[1]);assert.equal(channels.length,75);for(const channel of channels)assert.ok(handlers.has(channel),channel);});
test('Rechaza sesión ausente y origen externo',async()=>{assert.equal((await fetch(base+'/rpc',{method:'POST',body:'{}'})).status,400);assert.equal((await fetch(base+'/rpc',{method:'POST',headers:{Cookie:cookie,Origin:'https://otro.example'},body:'{}'})).status,403);});
test('Crea empresa con migraciones originales',async()=>{const b=await rpc('empresa:seleccionar',[],{companyName:'Prueba A',companyId:null});company=b.companyId;assert.equal(b.value.success,true);assert.match(company,/^[a-f0-9-]{36}$/);assert.equal((await rpc('empresa:update-info',[{nombre:'Prueba A',ruc:'20123456789',direccion:'Prueba',telefono:'',correo:'',periodo:'2026',logo:null}])).value.success,true);});
test('Rechaza directorios arbitrarios',async()=>{const r=await fetch(base+'/rpc',{method:'POST',headers:{Cookie:cookie},body:JSON.stringify({channel:'empresa:conectar-directa',args:['/etc'],companyId:company})});assert.equal(r.status,400);});
test('Conserva reglas y creación de cuentas',async()=>{assert.equal((await rpc('plan-cuentas:add',[{codigo:'10',descripcion:'Inválida'}])).value.success,false);for(const [codigo,descripcion]of [['1011','Caja'],['7011','Ventas'],['6011','Compras']])assert.equal((await rpc('plan-cuentas:add',[{codigo,descripcion}])).value.success,true);assert.equal((await rpc('plan-cuentas:get')).value.filter(x=>['1011','7011','6011'].includes(x.codigo)).length,3);});
const voucher={origen:'5',fechaContable:'2026-10-07',periodo:'2026-10',glosa:'Prueba web',detalles:[{cuenta:'1011',nombre_cuenta:'Caja',debe:118,haber:0},{cuenta:'7011',nombre_cuenta:'Ventas',debe:0,haber:118}]};
test('Preserva cuadre, correlativo y búsqueda',async()=>{const bad=structuredClone(voucher);bad.detalles[1].haber=100;assert.equal((await rpc('voucher:add',[bad])).value.success,false);const result=(await rpc('voucher:add',[voucher])).value;assert.equal(result.success,true);assert.equal(result.numero_voucher,1);const found=(await rpc('voucher:buscar',[{id:result.id}])).value;assert.equal(found.cabecera.total_debe,118);assert.equal(found.detalles.length,2);assert.equal((await rpc('voucher:get-siguiente-numero',[{origen:'5',periodo:'2026-10'}])).value.numero,2);});
test('Aísla dos empresas e IDs desconocidos',async()=>{second=(await rpc('empresa:seleccionar',[],{companyName:'Prueba B'})).companyId;assert.notEqual(company,second);assert.equal((await rpc('voucher:buscar',[{id:1}],{companyId:second})).value.success,false);assert.equal((await rpc('plan-cuentas:get',[],{companyId:second})).value.some(x=>x.codigo==='1011'),false);const r=await fetch(base+'/rpc',{method:'POST',headers:{Cookie:cookie},body:JSON.stringify({channel:'get-monedas',companyId:'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa'})});assert.equal(r.status,400);});
test('Mantiene contexto durante operaciones simultáneas',async()=>{const workspace=path.join(process.env.ANSORITO_DATA_DIR,'revision-local');const result=await Promise.all([company,second].map((companyId,i)=>storage.run({workspace,companyId},async()=>{await new Promise(r=>setTimeout(r,i?1:15));return db.getDB().prepare('SELECT COUNT(*) AS n FROM vouchers').get().n;})));assert.deepEqual(result,[1,0]);});
test('Dashboard HTTP coincide con el controlador original',async()=>{const c={workspace:path.join(process.env.ANSORITO_DATA_DIR,'revision-local'),companyId:company};const expected=storage.run(c,()=>require('../src/main/controllers/dashboardController').getDashboardData());assert.deepEqual((await rpc('dashboard:get-data')).value,JSON.parse(JSON.stringify(expected)));});
const report={tipo:'libro-diario',desde:'2026-01-01',hasta:'2026-12-31'};
test('Genera PDF y Excel originales y aísla descargas',async()=>{for(const channel of ['reportes:generar-pdf','reportes:exportar-excel']){const value=(await rpc(channel,[report])).value;assert.equal(value.success,true,value.error);assert.ok(value.download);const r=await fetch(base+'/download/'+value.download+'?company='+company,{headers:{Cookie:cookie}});assert.equal(r.status,200);const bytes=Buffer.from(await r.arrayBuffer());assert.ok(bytes.length>1000);assert.equal(bytes.subarray(0,channel.endsWith('pdf')?4:2).toString(),channel.endsWith('pdf')?'%PDF':'PK');assert.equal((await fetch(base+'/download/'+value.download+'?company='+second,{headers:{Cookie:cookie}})).status,404);}});
test('Guardar rechaza rutas enviadas por el cliente',async()=>{const r=await fetch(base+'/rpc',{method:'POST',headers:{Cookie:cookie},body:JSON.stringify({channel:'reportes:guardar-pdf',companyId:company,args:[{filePath:'/etc/passwd'}]})});assert.equal(r.status,400);});
test('Nueve familias de reportes coinciden con el controlador',async()=>{for(const tipo of ['registro-ventas','registro-compras','libro-diario','libro-mayor','balance-comprobacion','estado-resultados','situacion-financiera','notas-eeff','notas-er']){const params={...report,tipo,nivel:4};const c={workspace:path.join(process.env.ANSORITO_DATA_DIR,'revision-local'),companyId:company};const expected=storage.run(c,()=>require('../src/main/controllers/reportesController').previsualizar(params));assert.deepEqual((await rpc('reportes:previsualizar',[params])).value,JSON.parse(JSON.stringify(expected)),tipo);}});
test('Reintentos de red no duplican asientos',async()=>{const requestId=require('node:crypto').randomUUID();const first=await rpc('voucher:add',[voucher],{requestId});const retry=await rpc('voucher:add',[voucher],{requestId});assert.deepEqual(first.value,retry.value);assert.equal((await rpc('voucher:get-siguiente-numero',[{origen:'5',periodo:'2026-10'}])).value.numero,3);});
test('Edición conserva reglas y rechaza una versión antigua',async()=>{const loaded=(await rpc('voucher:buscar',[{id:1}])).value;const detalles=loaded.detalles.map(d=>({...d,debe:d.debe?120:0,haber:d.haber?120:0}));const params={voucher_id:1,detalles,webVersion:loaded.webVersion};assert.equal((await rpc('voucher:update-completo',[params])).value.success,true);const stale=(await rpc('voucher:update-completo',[params])).value;assert.equal(stale.success,false);assert.match(stale.error,/otra sesión/);assert.equal((await rpc('voucher:buscar',[{id:1}])).value.cabecera.total_debe,120);});
test('Compras y ventas conservan duplicados y datos SIRE locales',async()=>{for(const origen of ['8','14']){const v=structuredClone(voucher);v.origen=origen;v.detalles=v.detalles.map(d=>({...d,doc_tipo:'01',doc_numero:origen==='8'?'F001-100':'F001-200',fecha_doc:'2026-10-07',codigo:'20123456789',razon_social:'Entidad prueba',fecha_venc:'2026-11-07'}));assert.equal((await rpc('voucher:add',[v])).value.success,true);const duplicate=(await rpc('voucher:add',[v])).value;assert.equal(duplicate.success,false);assert.match(duplicate.error,/DUPLICADO/);const tipo=origen==='8'?'compras':'ventas';const result=(await rpc('sire:datos',[{tipo,desde:'2026-10-01',hasta:'2026-10-31'}])).value;assert.equal(result.success,true);assert.ok(result.filas.length>0);const txt=(await rpc('sire:exportar-txt',[{tipo,desde:'2026-10-01',hasta:'2026-10-31'}])).value;assert.equal(txt.success,true);assert.match(txt.defaultName,/DIAGNOSTICO/);}});
test('Monedas, amarres, cartera y notas permanecen operativos',async()=>{assert.equal((await rpc('add-moneda',[{fecha:'2026-10-07',nombre:'USD',tipo_cambio:3.8,compra:3.7,venta:3.8}])).value.success,true);assert.ok((await rpc('get-monedas')).value.length>0);assert.equal((await rpc('amarres:add',[{nombre:'Ventas prueba',tipo:'VENTA',prefijo:'7',doc_tipo:'01',moneda:'PEN',cuenta_destino:'1011',cuenta_igv:'4011'}])).value.success,true);assert.ok((await rpc('amarres:get')).value.some(x=>x.nombre==='Ventas prueba'));for(const channel of ['cartera:get-vencimientos','config-er:get','notas-eeff:get','sire:codificacion-get','sire-sunat:logs','sire-sunat:operaciones'])assert.notEqual((await rpc(channel,[{desde:'2026-10-01',hasta:'2026-10-31'}])).value,undefined,channel);});
test('Respaldos consistentes se reimportan sin modificar la empresa de origen',async()=>{const value=(await rpc('web:backup-database',['company'])).value;assert.equal(value.success,true);const r=await fetch(base+'/download/'+value.download+'?company='+company,{headers:{Cookie:cookie}});const buffer=Buffer.from(await r.arrayBuffer());assert.equal(buffer.subarray(0,16).toString(),'SQLite format 3\0');const result=await rpc('web:import-database',[{name:'Copia importada',kind:'company',base64:buffer.toString('base64')}]);assert.equal(result.value.success,true);assert.equal(result.value.vouchers,4);assert.equal((await rpc('voucher:buscar',[{id:1}],{companyId:result.companyId})).value.cabecera.total_debe,120);assert.notEqual(result.companyId,company);});
test('Importación rechaza archivos falsos y catálogo global sobre datos existentes',async()=>{for(const input of [{name:'Mal',base64:Buffer.from('mal').toString('base64')},{name:'Mal',kind:'global',base64:fs.readFileSync(path.join(process.env.ANSORITO_DATA_DIR,'revision-local','companies',company,'contable.db')).toString('base64')}]){const r=await fetch(base+'/rpc',{method:'POST',headers:{Cookie:cookie},body:JSON.stringify({channel:'web:import-database',companyId:company,args:[input]})});assert.equal(r.status,400);}});
test('Catálogo global se comparte entre empresas del mismo espacio y se aísla de otro usuario',async()=>{assert.equal((await rpc('plan-cuentas:add',[{codigo:'99991',descripcion:'Global prueba'}],{companyId:null})).value.success,true);assert.ok((await rpc('plan-cuentas:get',[],{companyId:second})).value.some(x=>x.codigo==='99991'));const workspace=path.join(process.env.ANSORITO_DATA_DIR,'otro-usuario');fs.mkdirSync(workspace);const rows=storage.run({workspace,companyId:null},()=>require('../src/main/controllers/planCuentasController').getPlanCuentas());assert.equal(rows.some(x=>x.codigo==='99991'),false);});
test('Carga Excel en los tres catálogos y preserva ámbito Local/Global',async()=>{const XLSX=require('xlsx');for(const [channel,rows,getter,codigo]of [['plan-cuentas:import-excel',[['CODIGO','DESCRIPCION'],['10555','Cuenta importada']],'plan-cuentas:get','10555'],['documentos:import-excel',[['CODIGO','DESCRIPCION'],['01','Factura']],'documentos:get','01'],['entidades:import-excel',[['RUC','RAZON SOCIAL','TIPO'],['20999999999','Entidad importada','Proveedor']],'entidades:get','20999999999']]){const book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,XLSX.utils.aoa_to_sheet(rows),'Catalogo');const base64=XLSX.write(book,{type:'base64',bookType:'xlsx'});const value=(await rpc(channel,[],{scope:'Local',upload:{name:'catalogo.xlsx',base64}})).value;assert.equal(value.success,true,value.error);assert.equal(value.count,1);assert.ok((await rpc(getter)).value.some(x=>x.codigo===codigo));assert.equal((await rpc(getter,[],{companyId:second})).value.some(x=>x.codigo===codigo),false);}});


test('Compras distingue proveedores y tipos, y rechaza duplicados al editar', async()=>{
 const base=structuredClone(voucher); base.origen='8';
 base.detalles=base.detalles.map(d=>({...d,doc_tipo:'01',doc_numero:'F901-900',codigo:'20111111111'}));
 const first=(await rpc('voucher:add',[base])).value;assert.equal(first.success,true,first.error);
 const other=structuredClone(base);other.detalles.forEach(d=>d.codigo='20222222222');
 const second=(await rpc('voucher:add',[other])).value;assert.equal(second.success,true,second.error);
 assert.equal((await rpc('voucher:add',[base])).value.success,false);
 const otherType=structuredClone(base);otherType.detalles.forEach(d=>d.doc_tipo='03');
 assert.equal((await rpc('voucher:add',[otherType])).value.success,true);
 const found=(await rpc('voucher:buscar',[{id:second.id}])).value;
 const detalles=found.detalles.map(d=>({...d,codigo:'20111111111'}));
 const edited=(await rpc('voucher:update-completo',[{voucher_id:second.id,detalles,webVersion:found.webVersion}])).value;
 assert.equal(edited.success,false);assert.match(edited.error,/DUPLICADO/);
});


test('Ficha tributaria inconsistente rechaza el guardado completo sin crear asientos',async()=>{
 const data=structuredClone(voucher);data.origen='14';
 data.detalles=data.detalles.map(d=>({...d,doc_tipo:'01',doc_numero:'F908-900',codigo:'20111111111'}));
 data.tributario={tipo_registro:'VENTA',venta:{base_gravada:50,igv:18,importe_total:118}};
 const result=(await rpc('voucher:add',[data])).value;assert.equal(result.success,false);assert.match(result.error,/suma del detalle/i);
 data.tributario.venta.base_gravada=100;
 const saved=(await rpc('voucher:add',[data])).value;assert.equal(saved.success,true,saved.error);
 const found=(await rpc('voucher:buscar',[{id:saved.id}])).value;
 assert.equal(found.tributario.venta.base_gravada,100);
});

 test('La búsqueda por período/factura usa la misma versión que la edición y rechaza reutilizarla',async()=>{
 const direct=(await rpc('voucher:buscar',[{id:1}])).value;
 for(const docNumero of ['',direct.detalles[0].doc_numero]) {
  const found=(await rpc('voucher:buscar-factura',[{periodo:direct.cabecera.periodo,docNumero,origen:direct.cabecera.origen}])).value;
  assert.equal(found.success,true);
  const canonical=(await rpc('voucher:buscar',[{id:found.cabecera.id}])).value;
  assert.equal(found.webVersion,canonical.webVersion);
 }
 const params={voucher_id:direct.cabecera.id,detalles:direct.detalles.map(d=>({...d,glosa:'Prueba versión de búsqueda'})),webVersion:direct.webVersion};
 assert.equal((await rpc('voucher:update-completo',[params])).value.success,true);
 assert.equal((await rpc('voucher:update-completo',[params])).value.success,false);
 });
