-- Generated from the original desktop migrations. Review changes in this file before deployment.
-- Run through tools/apply-postgres-schema.cjs; requires a private PostgreSQL connection.
CREATE SCHEMA IF NOT EXISTS ansorito;
REVOKE ALL ON SCHEMA ansorito FROM PUBLIC;
GRANT USAGE ON SCHEMA ansorito TO authenticated;
CREATE TABLE ansorito.empresas (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id),
  nombre text NOT NULL CHECK (length(trim(nombre)) > 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (owner_id, id)
);
ALTER TABLE ansorito.empresas ENABLE ROW LEVEL SECURITY;
ALTER TABLE ansorito.empresas FORCE ROW LEVEL SECURITY;
CREATE POLICY empresa_owner ON ansorito.empresas TO authenticated
  USING (owner_id = auth.uid()) WITH CHECK (owner_id = auth.uid());
GRANT SELECT, INSERT, UPDATE, DELETE ON ansorito.empresas TO authenticated;
CREATE FUNCTION ansorito.current_scope() RETURNS uuid LANGUAGE sql STABLE
SET search_path = pg_catalog AS $$
  SELECT nullif(current_setting('ansorito.scope_id', true), '')::uuid
$$;
REVOKE ALL ON FUNCTION ansorito.current_scope() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION ansorito.current_scope() TO authenticated;

CREATE TABLE ansorito."config_empresa" (
  owner_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id),
  scope_id uuid NOT NULL DEFAULT ansorito.current_scope(),
  "id" integer NOT NULL,
  "nombre_comercial" text,
  "ruc" text,
  "direccion_fiscal" text,
  "telefono" text,
  "correo" text,
  "periodo_contable" text,
  "logo" text,
  PRIMARY KEY (scope_id, "id"),
  UNIQUE (scope_id, "ruc"),
  CHECK (id = 1)
);
ALTER TABLE ansorito."config_empresa" ENABLE ROW LEVEL SECURITY;
ALTER TABLE ansorito."config_empresa" FORCE ROW LEVEL SECURITY;
CREATE POLICY isolated_scope ON ansorito."config_empresa" TO authenticated
  USING (owner_id = auth.uid() AND scope_id = ansorito.current_scope() AND (EXISTS (SELECT 1 FROM ansorito.empresas e WHERE e.id = scope_id AND e.owner_id = auth.uid()))) WITH CHECK (owner_id = auth.uid() AND scope_id = ansorito.current_scope() AND (EXISTS (SELECT 1 FROM ansorito.empresas e WHERE e.id = scope_id AND e.owner_id = auth.uid())));
GRANT SELECT, INSERT, UPDATE, DELETE ON ansorito."config_empresa" TO authenticated;

CREATE TABLE ansorito."plan_cuentas" (
  owner_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id),
  scope_id uuid NOT NULL DEFAULT ansorito.current_scope(),
  "id" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
  "codigo" text NOT NULL,
  "descripcion" text NOT NULL,
  "tipo" text,
  "nivel" integer,
  "estado_resultados" integer NOT NULL DEFAULT 0,
  PRIMARY KEY (scope_id, "id"),
  UNIQUE (scope_id, "codigo")
);
ALTER TABLE ansorito."plan_cuentas" ENABLE ROW LEVEL SECURITY;
ALTER TABLE ansorito."plan_cuentas" FORCE ROW LEVEL SECURITY;
CREATE POLICY isolated_scope ON ansorito."plan_cuentas" TO authenticated
  USING (owner_id = auth.uid() AND scope_id = ansorito.current_scope() AND (scope_id = auth.uid() OR EXISTS (SELECT 1 FROM ansorito.empresas e WHERE e.id = scope_id AND e.owner_id = auth.uid()))) WITH CHECK (owner_id = auth.uid() AND scope_id = ansorito.current_scope() AND (scope_id = auth.uid() OR EXISTS (SELECT 1 FROM ansorito.empresas e WHERE e.id = scope_id AND e.owner_id = auth.uid())));
GRANT SELECT, INSERT, UPDATE, DELETE ON ansorito."plan_cuentas" TO authenticated;

CREATE TABLE ansorito."tipos_documentos" (
  owner_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id),
  scope_id uuid NOT NULL DEFAULT ansorito.current_scope(),
  "id" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
  "codigo" text NOT NULL,
  "descripcion" text NOT NULL,
  PRIMARY KEY (scope_id, "id"),
  UNIQUE (scope_id, "codigo")
);
ALTER TABLE ansorito."tipos_documentos" ENABLE ROW LEVEL SECURITY;
ALTER TABLE ansorito."tipos_documentos" FORCE ROW LEVEL SECURITY;
CREATE POLICY isolated_scope ON ansorito."tipos_documentos" TO authenticated
  USING (owner_id = auth.uid() AND scope_id = ansorito.current_scope() AND (scope_id = auth.uid() OR EXISTS (SELECT 1 FROM ansorito.empresas e WHERE e.id = scope_id AND e.owner_id = auth.uid()))) WITH CHECK (owner_id = auth.uid() AND scope_id = ansorito.current_scope() AND (scope_id = auth.uid() OR EXISTS (SELECT 1 FROM ansorito.empresas e WHERE e.id = scope_id AND e.owner_id = auth.uid())));
GRANT SELECT, INSERT, UPDATE, DELETE ON ansorito."tipos_documentos" TO authenticated;

CREATE TABLE ansorito."entidades" (
  owner_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id),
  scope_id uuid NOT NULL DEFAULT ansorito.current_scope(),
  "id" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
  "codigo" text NOT NULL,
  "razon_social" text NOT NULL,
  "tipo" text NOT NULL,
  "tipo_documento" text DEFAULT '',
  PRIMARY KEY (scope_id, "id"),
  UNIQUE (scope_id, "codigo")
);
ALTER TABLE ansorito."entidades" ENABLE ROW LEVEL SECURITY;
ALTER TABLE ansorito."entidades" FORCE ROW LEVEL SECURITY;
CREATE POLICY isolated_scope ON ansorito."entidades" TO authenticated
  USING (owner_id = auth.uid() AND scope_id = ansorito.current_scope() AND (scope_id = auth.uid() OR EXISTS (SELECT 1 FROM ansorito.empresas e WHERE e.id = scope_id AND e.owner_id = auth.uid()))) WITH CHECK (owner_id = auth.uid() AND scope_id = ansorito.current_scope() AND (scope_id = auth.uid() OR EXISTS (SELECT 1 FROM ansorito.empresas e WHERE e.id = scope_id AND e.owner_id = auth.uid())));
GRANT SELECT, INSERT, UPDATE, DELETE ON ansorito."entidades" TO authenticated;

CREATE TABLE ansorito."amarres_asistente" (
  owner_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id),
  scope_id uuid NOT NULL DEFAULT ansorito.current_scope(),
  "id" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 3) NOT NULL,
  "nombre" text NOT NULL,
  "tipo" text NOT NULL,
  "prefijo" text NOT NULL,
  "doc_tipo" text DEFAULT '',
  "cuenta_igv" text,
  "cuenta_igv_exo" text,
  "cuenta_igv_ina" text,
  "cuenta_destino" text NOT NULL,
  "moneda" text DEFAULT 'PEN',
  "activo" integer NOT NULL DEFAULT 1,
  PRIMARY KEY (scope_id, "id")
);
ALTER TABLE ansorito."amarres_asistente" ENABLE ROW LEVEL SECURITY;
ALTER TABLE ansorito."amarres_asistente" FORCE ROW LEVEL SECURITY;
CREATE POLICY isolated_scope ON ansorito."amarres_asistente" TO authenticated
  USING (owner_id = auth.uid() AND scope_id = ansorito.current_scope() AND (EXISTS (SELECT 1 FROM ansorito.empresas e WHERE e.id = scope_id AND e.owner_id = auth.uid()))) WITH CHECK (owner_id = auth.uid() AND scope_id = ansorito.current_scope() AND (EXISTS (SELECT 1 FROM ansorito.empresas e WHERE e.id = scope_id AND e.owner_id = auth.uid())));
GRANT SELECT, INSERT, UPDATE, DELETE ON ansorito."amarres_asistente" TO authenticated;

CREATE TABLE ansorito."voucher_detalles" (
  owner_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id),
  scope_id uuid NOT NULL DEFAULT ansorito.current_scope(),
  "id" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
  "voucher_id" integer NOT NULL,
  "cuenta" text NOT NULL,
  "nombre_cuenta" text,
  "debe" numeric DEFAULT 0,
  "haber" numeric DEFAULT 0,
  "moneda" text DEFAULT 'PEN',
  "tc" numeric DEFAULT 1,
  "equivalente" numeric DEFAULT 0,
  "doc_tipo" text,
  "doc_numero" text,
  "fecha_doc" text,
  "fecha_venc" text,
  "codigo" text,
  "razon_social" text,
  "glosa" text,
  PRIMARY KEY (scope_id, "id")
);
ALTER TABLE ansorito."voucher_detalles" ENABLE ROW LEVEL SECURITY;
ALTER TABLE ansorito."voucher_detalles" FORCE ROW LEVEL SECURITY;
CREATE POLICY isolated_scope ON ansorito."voucher_detalles" TO authenticated
  USING (owner_id = auth.uid() AND scope_id = ansorito.current_scope() AND (EXISTS (SELECT 1 FROM ansorito.empresas e WHERE e.id = scope_id AND e.owner_id = auth.uid()))) WITH CHECK (owner_id = auth.uid() AND scope_id = ansorito.current_scope() AND (EXISTS (SELECT 1 FROM ansorito.empresas e WHERE e.id = scope_id AND e.owner_id = auth.uid())));
GRANT SELECT, INSERT, UPDATE, DELETE ON ansorito."voucher_detalles" TO authenticated;

CREATE TABLE ansorito."vouchers" (
  owner_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id),
  scope_id uuid NOT NULL DEFAULT ansorito.current_scope(),
  "id" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
  "origen" text NOT NULL,
  "numero_voucher" integer NOT NULL DEFAULT 0,
  "fecha" text NOT NULL,
  "periodo" text NOT NULL DEFAULT '',
  "glosa_cabecera" text,
  "total_debe" numeric DEFAULT 0,
  "total_haber" numeric DEFAULT 0,
  "fecha_creacion" text DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'America/Lima', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (scope_id, "id")
);
ALTER TABLE ansorito."vouchers" ENABLE ROW LEVEL SECURITY;
ALTER TABLE ansorito."vouchers" FORCE ROW LEVEL SECURITY;
CREATE POLICY isolated_scope ON ansorito."vouchers" TO authenticated
  USING (owner_id = auth.uid() AND scope_id = ansorito.current_scope() AND (EXISTS (SELECT 1 FROM ansorito.empresas e WHERE e.id = scope_id AND e.owner_id = auth.uid()))) WITH CHECK (owner_id = auth.uid() AND scope_id = ansorito.current_scope() AND (EXISTS (SELECT 1 FROM ansorito.empresas e WHERE e.id = scope_id AND e.owner_id = auth.uid())));
GRANT SELECT, INSERT, UPDATE, DELETE ON ansorito."vouchers" TO authenticated;

CREATE TABLE ansorito."comprobantes_tributarios" (
  owner_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id),
  scope_id uuid NOT NULL DEFAULT ansorito.current_scope(),
  "id" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
  "voucher_id" integer NOT NULL,
  "tipo_registro" text NOT NULL,
  "fecha_emision" text,
  "fecha_vencimiento" text,
  "tipo_documento" text,
  "serie" text,
  "numero" text,
  "tipo_doc_identidad" text,
  "numero_doc_identidad" text,
  "razon_social" text,
  "moneda" text DEFAULT 'PEN',
  "tipo_cambio" numeric DEFAULT 1,
  "ref_fecha" text,
  "ref_tipo_documento" text,
  "ref_serie" text,
  "ref_numero" text,
  "car_sunat" text,
  "fuente" text NOT NULL DEFAULT 'MANUAL',
  "requiere_revision" integer NOT NULL DEFAULT 0,
  "created_at" text DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'America/Lima', 'YYYY-MM-DD HH24:MI:SS'),
  "updated_at" text DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'America/Lima', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (scope_id, "id"),
  UNIQUE (scope_id, "voucher_id"),
  CHECK (tipo_registro IN ('VENTA','COMPRA'))
);
ALTER TABLE ansorito."comprobantes_tributarios" ENABLE ROW LEVEL SECURITY;
ALTER TABLE ansorito."comprobantes_tributarios" FORCE ROW LEVEL SECURITY;
CREATE POLICY isolated_scope ON ansorito."comprobantes_tributarios" TO authenticated
  USING (owner_id = auth.uid() AND scope_id = ansorito.current_scope() AND (EXISTS (SELECT 1 FROM ansorito.empresas e WHERE e.id = scope_id AND e.owner_id = auth.uid()))) WITH CHECK (owner_id = auth.uid() AND scope_id = ansorito.current_scope() AND (EXISTS (SELECT 1 FROM ansorito.empresas e WHERE e.id = scope_id AND e.owner_id = auth.uid())));
GRANT SELECT, INSERT, UPDATE, DELETE ON ansorito."comprobantes_tributarios" TO authenticated;

CREATE TABLE ansorito."comprobante_venta" (
  owner_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id),
  scope_id uuid NOT NULL DEFAULT ansorito.current_scope(),
  "comprobante_id" integer NOT NULL,
  "valor_exportacion" numeric DEFAULT 0,
  "base_gravada" numeric DEFAULT 0,
  "descuento_base" numeric DEFAULT 0,
  "igv" numeric DEFAULT 0,
  "descuento_igv" numeric DEFAULT 0,
  "importe_exonerado" numeric DEFAULT 0,
  "importe_inafecto" numeric DEFAULT 0,
  "isc" numeric DEFAULT 0,
  "base_ivap" numeric DEFAULT 0,
  "ivap" numeric DEFAULT 0,
  "icbper" numeric DEFAULT 0,
  "otros_tributos" numeric DEFAULT 0,
  "importe_total" numeric DEFAULT 0,
  PRIMARY KEY (scope_id, "comprobante_id")
);
ALTER TABLE ansorito."comprobante_venta" ENABLE ROW LEVEL SECURITY;
ALTER TABLE ansorito."comprobante_venta" FORCE ROW LEVEL SECURITY;
CREATE POLICY isolated_scope ON ansorito."comprobante_venta" TO authenticated
  USING (owner_id = auth.uid() AND scope_id = ansorito.current_scope() AND (EXISTS (SELECT 1 FROM ansorito.empresas e WHERE e.id = scope_id AND e.owner_id = auth.uid()))) WITH CHECK (owner_id = auth.uid() AND scope_id = ansorito.current_scope() AND (EXISTS (SELECT 1 FROM ansorito.empresas e WHERE e.id = scope_id AND e.owner_id = auth.uid())));
GRANT SELECT, INSERT, UPDATE, DELETE ON ansorito."comprobante_venta" TO authenticated;

CREATE TABLE ansorito."comprobante_compra" (
  owner_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id),
  scope_id uuid NOT NULL DEFAULT ansorito.current_scope(),
  "comprobante_id" integer NOT NULL,
  "g1_base" numeric DEFAULT 0,
  "g1_igv" numeric DEFAULT 0,
  "g2_base" numeric DEFAULT 0,
  "g2_igv" numeric DEFAULT 0,
  "g3_base" numeric DEFAULT 0,
  "g3_igv" numeric DEFAULT 0,
  "valor_no_gravado" numeric DEFAULT 0,
  "isc" numeric DEFAULT 0,
  "icbper" numeric DEFAULT 0,
  "otros_tributos" numeric DEFAULT 0,
  "importe_total" numeric DEFAULT 0,
  "detraccion_numero" text,
  "detraccion_fecha" text,
  "marca_retencion" text,
  PRIMARY KEY (scope_id, "comprobante_id")
);
ALTER TABLE ansorito."comprobante_compra" ENABLE ROW LEVEL SECURITY;
ALTER TABLE ansorito."comprobante_compra" FORCE ROW LEVEL SECURITY;
CREATE POLICY isolated_scope ON ansorito."comprobante_compra" TO authenticated
  USING (owner_id = auth.uid() AND scope_id = ansorito.current_scope() AND (EXISTS (SELECT 1 FROM ansorito.empresas e WHERE e.id = scope_id AND e.owner_id = auth.uid()))) WITH CHECK (owner_id = auth.uid() AND scope_id = ansorito.current_scope() AND (EXISTS (SELECT 1 FROM ansorito.empresas e WHERE e.id = scope_id AND e.owner_id = auth.uid())));
GRANT SELECT, INSERT, UPDATE, DELETE ON ansorito."comprobante_compra" TO authenticated;

CREATE TABLE ansorito."sire_config" (
  owner_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id),
  scope_id uuid NOT NULL DEFAULT ansorito.current_scope(),
  "id" integer NOT NULL,
  "ruc" text,
  "usuario_sol" text,
  "clave_sol_enc" text,
  "client_id" text,
  "client_secret_enc" text,
  "scope" text DEFAULT 'https://api-sire.sunat.gob.pe',
  "seguridad_base_url" text DEFAULT 'https://api-seguridad.sunat.gob.pe',
  "sire_base_url" text DEFAULT 'https://api-sire.sunat.gob.pe',
  "access_token_enc" text,
  "token_expires_at" text,
  "estado_conexion" text DEFAULT 'NO_CONFIGURADO',
  "updated_at" text DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'America/Lima', 'YYYY-MM-DD HH24:MI:SS'),
  "cuenta_gasto" text DEFAULT '',
  "cuenta_ingreso" text DEFAULT '',
  "cuenta_igv_compras" text DEFAULT '',
  "cuenta_igv_ventas" text DEFAULT '',
  "cuenta_cxp" text DEFAULT '',
  "cuenta_cxc" text DEFAULT '',
  PRIMARY KEY (scope_id, "id"),
  CHECK (id = 1)
);
ALTER TABLE ansorito."sire_config" ENABLE ROW LEVEL SECURITY;
ALTER TABLE ansorito."sire_config" FORCE ROW LEVEL SECURITY;
CREATE POLICY isolated_scope ON ansorito."sire_config" TO authenticated
  USING (owner_id = auth.uid() AND scope_id = ansorito.current_scope() AND (EXISTS (SELECT 1 FROM ansorito.empresas e WHERE e.id = scope_id AND e.owner_id = auth.uid()))) WITH CHECK (owner_id = auth.uid() AND scope_id = ansorito.current_scope() AND (EXISTS (SELECT 1 FROM ansorito.empresas e WHERE e.id = scope_id AND e.owner_id = auth.uid())));
GRANT SELECT, INSERT, UPDATE, DELETE ON ansorito."sire_config" TO authenticated;

CREATE TABLE ansorito."sire_operaciones" (
  owner_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id),
  scope_id uuid NOT NULL DEFAULT ansorito.current_scope(),
  "id" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
  "tipo" text NOT NULL,
  "periodo" text NOT NULL,
  "operacion" text NOT NULL,
  "ticket" text,
  "estado" text,
  "archivo_nombre" text,
  "archivo_path" text,
  "mensaje" text,
  "created_at" text DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'America/Lima', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (scope_id, "id")
);
ALTER TABLE ansorito."sire_operaciones" ENABLE ROW LEVEL SECURITY;
ALTER TABLE ansorito."sire_operaciones" FORCE ROW LEVEL SECURITY;
CREATE POLICY isolated_scope ON ansorito."sire_operaciones" TO authenticated
  USING (owner_id = auth.uid() AND scope_id = ansorito.current_scope() AND (EXISTS (SELECT 1 FROM ansorito.empresas e WHERE e.id = scope_id AND e.owner_id = auth.uid()))) WITH CHECK (owner_id = auth.uid() AND scope_id = ansorito.current_scope() AND (EXISTS (SELECT 1 FROM ansorito.empresas e WHERE e.id = scope_id AND e.owner_id = auth.uid())));
GRANT SELECT, INSERT, UPDATE, DELETE ON ansorito."sire_operaciones" TO authenticated;

CREATE TABLE ansorito."sire_logs" (
  owner_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id),
  scope_id uuid NOT NULL DEFAULT ansorito.current_scope(),
  "id" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
  "fecha" text DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'America/Lima', 'YYYY-MM-DD HH24:MI:SS'),
  "ruc" text,
  "tipo" text,
  "periodo" text,
  "operacion" text,
  "metodo" text,
  "endpoint" text,
  "status_code" integer,
  "success" integer,
  "mensaje" text,
  PRIMARY KEY (scope_id, "id")
);
ALTER TABLE ansorito."sire_logs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE ansorito."sire_logs" FORCE ROW LEVEL SECURITY;
CREATE POLICY isolated_scope ON ansorito."sire_logs" TO authenticated
  USING (owner_id = auth.uid() AND scope_id = ansorito.current_scope() AND (EXISTS (SELECT 1 FROM ansorito.empresas e WHERE e.id = scope_id AND e.owner_id = auth.uid()))) WITH CHECK (owner_id = auth.uid() AND scope_id = ansorito.current_scope() AND (EXISTS (SELECT 1 FROM ansorito.empresas e WHERE e.id = scope_id AND e.owner_id = auth.uid())));
GRANT SELECT, INSERT, UPDATE, DELETE ON ansorito."sire_logs" TO authenticated;

CREATE TABLE ansorito."config_notas_eeff" (
  owner_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id),
  scope_id uuid NOT NULL DEFAULT ansorito.current_scope(),
  "id" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
  "numero" text NOT NULL,
  "nombre" text NOT NULL,
  "categoria" text NOT NULL,
  "cuentas" text NOT NULL DEFAULT '[]',
  "orden" integer DEFAULT 0,
  PRIMARY KEY (scope_id, "id")
);
ALTER TABLE ansorito."config_notas_eeff" ENABLE ROW LEVEL SECURITY;
ALTER TABLE ansorito."config_notas_eeff" FORCE ROW LEVEL SECURITY;
CREATE POLICY isolated_scope ON ansorito."config_notas_eeff" TO authenticated
  USING (owner_id = auth.uid() AND scope_id = ansorito.current_scope() AND (EXISTS (SELECT 1 FROM ansorito.empresas e WHERE e.id = scope_id AND e.owner_id = auth.uid()))) WITH CHECK (owner_id = auth.uid() AND scope_id = ansorito.current_scope() AND (EXISTS (SELECT 1 FROM ansorito.empresas e WHERE e.id = scope_id AND e.owner_id = auth.uid())));
GRANT SELECT, INSERT, UPDATE, DELETE ON ansorito."config_notas_eeff" TO authenticated;

CREATE TABLE ansorito."config_estado_resultados" (
  owner_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id),
  scope_id uuid NOT NULL DEFAULT ansorito.current_scope(),
  "rubro" text NOT NULL,
  "nota_numero" text DEFAULT '',
  "cuentas" text NOT NULL DEFAULT '[]',
  "orden" integer NOT NULL DEFAULT 0,
  PRIMARY KEY (scope_id, "rubro")
);
ALTER TABLE ansorito."config_estado_resultados" ENABLE ROW LEVEL SECURITY;
ALTER TABLE ansorito."config_estado_resultados" FORCE ROW LEVEL SECURITY;
CREATE POLICY isolated_scope ON ansorito."config_estado_resultados" TO authenticated
  USING (owner_id = auth.uid() AND scope_id = ansorito.current_scope() AND (EXISTS (SELECT 1 FROM ansorito.empresas e WHERE e.id = scope_id AND e.owner_id = auth.uid()))) WITH CHECK (owner_id = auth.uid() AND scope_id = ansorito.current_scope() AND (EXISTS (SELECT 1 FROM ansorito.empresas e WHERE e.id = scope_id AND e.owner_id = auth.uid())));
GRANT SELECT, INSERT, UPDATE, DELETE ON ansorito."config_estado_resultados" TO authenticated;

CREATE TABLE ansorito."config_notas_er" (
  owner_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id),
  scope_id uuid NOT NULL DEFAULT ansorito.current_scope(),
  "id" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 19) NOT NULL,
  "numero" text NOT NULL DEFAULT '',
  "nombre" text NOT NULL,
  "bloque" text NOT NULL,
  "cuentas" text NOT NULL DEFAULT '[]',
  "orden" integer NOT NULL DEFAULT 0,
  "created_at" text DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'America/Lima', 'YYYY-MM-DD HH24:MI:SS'),
  "updated_at" text DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'America/Lima', 'YYYY-MM-DD HH24:MI:SS'),
  "concepto_key" text DEFAULT NULL,
  "preestablecida" integer NOT NULL DEFAULT 0,
  PRIMARY KEY (scope_id, "id")
);
ALTER TABLE ansorito."config_notas_er" ENABLE ROW LEVEL SECURITY;
ALTER TABLE ansorito."config_notas_er" FORCE ROW LEVEL SECURITY;
CREATE POLICY isolated_scope ON ansorito."config_notas_er" TO authenticated
  USING (owner_id = auth.uid() AND scope_id = ansorito.current_scope() AND (EXISTS (SELECT 1 FROM ansorito.empresas e WHERE e.id = scope_id AND e.owner_id = auth.uid()))) WITH CHECK (owner_id = auth.uid() AND scope_id = ansorito.current_scope() AND (EXISTS (SELECT 1 FROM ansorito.empresas e WHERE e.id = scope_id AND e.owner_id = auth.uid())));
GRANT SELECT, INSERT, UPDATE, DELETE ON ansorito."config_notas_er" TO authenticated;

CREATE TABLE ansorito."monedas" (
  owner_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id),
  scope_id uuid NOT NULL DEFAULT ansorito.current_scope(),
  "fecha" text NOT NULL,
  "nombre" text NOT NULL,
  "tipo_cambio" numeric NOT NULL,
  "compra" numeric DEFAULT 0,
  "venta" numeric DEFAULT 0,
  "fuente" text DEFAULT '',
  "fecha_fuente" text DEFAULT '',
  PRIMARY KEY (scope_id, "fecha", "nombre")
);
ALTER TABLE ansorito."monedas" ENABLE ROW LEVEL SECURITY;
ALTER TABLE ansorito."monedas" FORCE ROW LEVEL SECURITY;
CREATE POLICY isolated_scope ON ansorito."monedas" TO authenticated
  USING (owner_id = auth.uid() AND scope_id = ansorito.current_scope() AND (scope_id = auth.uid() OR EXISTS (SELECT 1 FROM ansorito.empresas e WHERE e.id = scope_id AND e.owner_id = auth.uid()))) WITH CHECK (owner_id = auth.uid() AND scope_id = ansorito.current_scope() AND (scope_id = auth.uid() OR EXISTS (SELECT 1 FROM ansorito.empresas e WHERE e.id = scope_id AND e.owner_id = auth.uid())));
GRANT SELECT, INSERT, UPDATE, DELETE ON ansorito."monedas" TO authenticated;
ALTER TABLE ansorito."voucher_detalles" ADD FOREIGN KEY (scope_id, "voucher_id") REFERENCES ansorito."vouchers" (scope_id, "id") ON DELETE CASCADE;
ALTER TABLE ansorito."comprobantes_tributarios" ADD FOREIGN KEY (scope_id, "voucher_id") REFERENCES ansorito."vouchers" (scope_id, "id") ON DELETE CASCADE;
ALTER TABLE ansorito."comprobante_venta" ADD FOREIGN KEY (scope_id, "comprobante_id") REFERENCES ansorito."comprobantes_tributarios" (scope_id, "id") ON DELETE CASCADE;
ALTER TABLE ansorito."comprobante_compra" ADD FOREIGN KEY (scope_id, "comprobante_id") REFERENCES ansorito."comprobantes_tributarios" (scope_id, "id") ON DELETE CASCADE;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA ansorito TO authenticated;
CREATE UNIQUE INDEX notas_er_concepto ON ansorito.config_notas_er (scope_id, concepto_key) WHERE concepto_key IS NOT NULL;
CREATE UNIQUE INDEX notas_er_numero ON ansorito.config_notas_er (scope_id, lower(trim(numero))) WHERE trim(numero) <> '';
CREATE INDEX voucher_periodo ON ansorito.vouchers (scope_id, periodo, fecha);
CREATE INDEX detalle_voucher ON ansorito.voucher_detalles (scope_id, voucher_id);
CREATE INDEX detalle_cuenta ON ansorito.voucher_detalles (scope_id, cuenta);
CREATE INDEX sire_periodo ON ansorito.sire_operaciones (scope_id, periodo, tipo);
