-- Company-owned configurable destinations. Existing accounting entries are untouched.
CREATE TABLE ansorito.asientos_automaticos (
 owner_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id),
 scope_id uuid NOT NULL DEFAULT ansorito.current_scope(),
 id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
 nombre text NOT NULL, prefijo text NOT NULL, origen text NOT NULL DEFAULT '*',
 cuenta_debe text NOT NULL, cuenta_haber text NOT NULL,
 porcentaje numeric NOT NULL CHECK(porcentaje > 0 AND porcentaje <= 100),
 activo integer NOT NULL CHECK(activo IN (0,1)), PRIMARY KEY(scope_id,id)
);
CREATE TABLE ansorito.asientos_automaticos_lineas (
 owner_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id),
 scope_id uuid NOT NULL DEFAULT ansorito.current_scope(),
 detalle_id integer NOT NULL, voucher_id integer NOT NULL, fuente_id integer NOT NULL,
 regla_json text NOT NULL, lado text NOT NULL CHECK(lado IN ('DEBE','HABER')),
 PRIMARY KEY(scope_id,detalle_id),
 FOREIGN KEY(scope_id,detalle_id) REFERENCES ansorito.voucher_detalles(scope_id,id) ON DELETE CASCADE,
 FOREIGN KEY(scope_id,fuente_id) REFERENCES ansorito.voucher_detalles(scope_id,id) ON DELETE CASCADE,
 FOREIGN KEY(scope_id,voucher_id) REFERENCES ansorito.vouchers(scope_id,id) ON DELETE CASCADE
);
DO $$ DECLARE t text; BEGIN
 FOREACH t IN ARRAY ARRAY['asientos_automaticos','asientos_automaticos_lineas'] LOOP
 EXECUTE format('ALTER TABLE ansorito.%I ENABLE ROW LEVEL SECURITY',t);
 EXECUTE format('ALTER TABLE ansorito.%I FORCE ROW LEVEL SECURITY',t);
 EXECUTE format('CREATE POLICY isolated_scope ON ansorito.%I TO authenticated USING (owner_id = auth.uid() AND scope_id = ansorito.current_scope() AND EXISTS (SELECT 1 FROM ansorito.empresas e WHERE e.id = scope_id AND e.owner_id = auth.uid())) WITH CHECK (owner_id = auth.uid() AND scope_id = ansorito.current_scope() AND EXISTS (SELECT 1 FROM ansorito.empresas e WHERE e.id = scope_id AND e.owner_id = auth.uid()))',t);
 EXECUTE format('GRANT SELECT,INSERT,UPDATE,DELETE ON ansorito.%I TO authenticated',t);
 END LOOP;
END $$;
GRANT USAGE, SELECT ON SEQUENCE ansorito.asientos_automaticos_id_seq TO authenticated;
CREATE INDEX automaticos_voucher ON ansorito.asientos_automaticos_lineas(scope_id,voucher_id);
